### ISSUE TITLE
Juicebox Field Formatter works on individual images but not on the whole pre-built galleries.

### ISSUE THREAD

**Issue by D4KO** [fkelly12054/juicebox-kelly#8]
fkelly reports:
Last night I was trying to reverse engineer the "protected functionstyleImage()" in JuiceboxFormatter. That is where we were hitting the dependency injection error because we were trying to do a " $style_obj = ImageStyle::load($style_each);" and that doesn't work anymore. I was puzzled that we didn't hit the error more frequently but looking at it, it seems to me that we only get into this section of code when we are trying to use the Juicebox Field Formatter on individual images that we are adding to a content type rather than loading up whole pre-built galleries the way I always do. And I mention that because I think it's important for testing going forward. People use the module differently and I'm not confident that we've covered all bases.

**Comment by D4KO** [comment]
This 'regression' propebly gets in to the code by previous commit #825643f (ImageStyle dependency injection refactoring).
May be it's not the regression at all. Needs more reverse engineering, as fkelly said, to figure out how Juicebox actually works with the image styles and pre-build galleries.
I've noticed earlier that pre-build galleries are rendered from some XML data that is propebly generated on the fly. This might be the tricky part.
I agree this is the release-blocker and we need to fix before we get stable.

**Comment by D4KO** [comment]
protected function styleImage() constructs and returns the array containing the styled image URL (resized, cropped, etc.) of the given file.
I'm not sure what you mean by 'and that doesn't work anymore.' Can you provide me more info please?
I promise I'll set my own clear D9 locally soon to be able to test thing myself and debug fully with the server error logs.

**Comment by fkelly12054** [comment]
I'm not sure what "that doesn't work anymore" means either.  I must have just been tired, sorry for any confusion.  I'm almost positive that the imagestyle "thing" we are talking about is just for an image or images that are being added in a content type and are NOT PART OF A PRE-BUILT gallery.  I think we are good with the fixes you have done to in the function styleImage( in the juiceboxformatter.php program ... specifically "$style_obj = $this->entityTypeManager->getStorage('image_style')->load($style_each);"  at line 344 because there was a LOT of work needed to make that statement work and replace the dependency injection error that was there.  We can (and should) test more but I think we are okay.
